In [2]:
import pandas as pd
df=pd.read_csv('C:\\Users\\Mojtaba\\Projects\\parkinsons\\Detecting-Parkinson-s-Disease-\\parkinsons.data')
df.head()

name  MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
0  phon_R01_S01_1      119.992       157.302        74.997         0.00784   
1  phon_R01_S01_2      122.400       148.650       113.819         0.00968   
2  phon_R01_S01_3      116.682       131.111       111.555         0.01050   
3  phon_R01_S01_4      116.676       137.871       111.366         0.00997   
4  phon_R01_S01_5      116.014       141.781       110.655         0.01284   

   MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  ...  \
0           0.00007   0.00370   0.00554     0.01109       0.04374  ...   
1           0.00008   0.00465   0.00696     0.01394       0.06134  ...   
2           0.00009   0.00544   0.00781     0.01633       0.05233  ...   
3           0.00009   0.00502   0.00698     0.01505       0.05492  ...   
4           0.00011   0.00655   0.00908     0.01966       0.06425  ...   

   Shimmer:DDA      NHR     HNR  status      RPDE       DFA   spread1  \
0      0.06545  0.02211  21.033       1  0.414783  0.815285 -4.813031   
1      0.09403  0.01929  19.085       1  0.458359  0.819521 -4.075192   
2      0.08270  0.01309  20.651       1  0.429895  0.825288 -4.443179   
3      0.08771  0.01353  20.644       1  0.434969  0.819235 -4.117501   
4      0.10470  0.01767  19.649       1  0.417356  0.823484 -3.747787   

    spread2        D2       PPE  
0  0.266482  2.301442  0.284654  
1  0.335590  2.486855  0.368674  
2  0.311173  2.342259  0.332634  
3  0.334147  2.405554  0.368975  
4  0.234513  2.332180  0.410335  

[5 rows x 24 columns]

In [3]:
claim = "Pluto is a planet!"
claim.lower()
# claim.startswith(planet)

'pluto is a planet!'

In [4]:
claim.index('plan')

11

In [5]:
claim.startswith('Pluto')

True

In [6]:
claim.endswith('dwarf planet')

False

In [7]:
planet="this is a great planet"
print("hello", end='')
print("pluto", end='')
len(planet)
# Yes, we can even loop over them
[char+'! ' for char in planet]

hellopluto

['t! ',
 'h! ',
 'i! ',
 's! ',
 ' ! ',
 'i! ',
 's! ',
 ' ! ',
 'a! ',
 ' ! ',
 'g! ',
 'r! ',
 'e! ',
 'a! ',
 't! ',
 ' ! ',
 'p! ',
 'l! ',
 'a! ',
 'n! ',
 'e! ',
 't! ']

In [8]:
words = claim.split()
words

['Pluto', 'is', 'a', 'planet!']

In [9]:
datestr = '1956-01-31'
year, month, day = datestr.split('-')

In [10]:
year

'1956'

In [11]:
'/'.join([month, day, year])

'01/31/1956'

In [12]:
' 👏 '.join([word.upper() for word in words])

'PLUTO 👏 IS 👏 A 👏 PLANET!'

In [13]:
planet='Pluto'
planet + ', we miss you.'

'Pluto, we miss you.'

In [14]:
position = 9
planet + ", you'll always be the " + str(position) + "th planet to me."

"Pluto, you'll always be the 9th planet to me."

In [15]:
"{}, you'll always be the {}th planet to me.".format(planet, position)

"Pluto, you'll always be the 9th planet to me."

In [16]:
pluto_mass = 1.303 * 10**22
earth_mass = 5.9722 * 10**24
population = 52910390
#         2 decimal points   3 decimal points, format as percent     separate with commas
"{} weighs about {:.2} kilograms ({:.3%} of Earth's mass). It is home to {:,} Plutonians.".format(
    planet, pluto_mass, pluto_mass / earth_mass, population,
)

"Pluto weighs about 1.3e+22 kilograms (0.218% of Earth's mass). It is home to 52,910,390 Plutonians."

In [17]:
# Referring to format() arguments by index, starting from 0
s = """Pluto's a {0}.
No, it's a {1}.
{0}!
{1}!""".format('planet', 'dwarf planet')
print(s)

Pluto's a planet.
No, it's a dwarf planet.
planet!
dwarf planet!


In [18]:
# Dictionary
numbers = {'one':1, 'two':2, 'three':3}
# add
numbers['eleven'] = 11
# change
numbers['one'] = 'Pluto'

planets = ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']
planet_to_initial = {planet: planet[0] for planet in planets}
planet_to_initial

{'Mercury': 'M',
 'Venus': 'V',
 'Earth': 'E',
 'Mars': 'M',
 'Jupiter': 'J',
 'Saturn': 'S',
 'Uranus': 'U',
 'Neptune': 'N'}

In [19]:
'Saturn' in planet_to_initial

True

In [20]:
for k in numbers:
    print("{} = {}".format(k, numbers[k]))

one = Pluto
two = 2
three = 3
eleven = 11


In [21]:
# Get all the initials, sort them alphabetically, and put them in a space-separated string.
' '.join(sorted(planet_to_initial.values()))

'E J M M N S U V'

In [25]:
for i, o in planet_to_initial.items():
    print("{} begins with \"{}\"".format(i.rjust(50), o.rjust(20)))

                                           Mercury begins with "                   M"
                                             Venus begins with "                   V"
                                             Earth begins with "                   E"
                                              Mars begins with "                   M"
                                           Jupiter begins with "                   J"
                                            Saturn begins with "                   S"
                                            Uranus begins with "                   U"
                                           Neptune begins with "                   N"


In [47]:
codes, uniques = pd.factorize(['ab', 'b', 'a', 'a', 'b','d', 'a', 'b'])
codes
# uniques

array([0, 1, 2, 2, 1, 3, 2, 1], dtype=int64)

In [80]:

# Solution
def word_search(documents, keyword):
    indices = [] 
    for i, doc in enumerate(documents):
        tokens = doc.split()
        normalized = [token.rstrip('.,').lower() for token in tokens]
        if keyword.lower() in normalized:
            indices.append(i)
    return indices


# word_search(documents,keyword)
def multi_word_search(documents, keywords):
    keyword_to_indices = {}
    for keyword in keywords:
        keyword_to_indices[keyword] = word_search(documents, keyword)
    return keyword_to_indices

documents = ["The Learn Python Challenge Casino.", "They bought a car and a casino", "Casinoville"]
keyword = ['casino', 'they']
# print(keyword_to_indices.keys)


In [92]:
import math
import sklearn.model_selection
print(dir(sklearn.model_selection))


['BaseCrossValidator', 'GridSearchCV', 'GroupKFold', 'GroupShuffleSplit', 'KFold', 'LeaveOneGroupOut', 'LeaveOneOut', 'LeavePGroupsOut', 'LeavePOut', 'ParameterGrid', 'ParameterSampler', 'PredefinedSplit', 'RandomizedSearchCV', 'RepeatedKFold', 'RepeatedStratifiedKFold', 'ShuffleSplit', 'StratifiedKFold', 'StratifiedShuffleSplit', 'TimeSeriesSplit', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_search', '_split', '_validation', 'check_cv', 'cross_val_predict', 'cross_val_score', 'cross_validate', 'fit_grid_point', 'learning_curve', 'permutation_test_score', 'train_test_split', 'validation_curve']


In [93]:
print("pi to 4 significant digits = {:.4}".format(math.pi))

pi to 4 significant digits = 3.142


In [95]:
math.log(32, 2)
help(math.log)

Help on built-in function log in module math:

log(...)
    log(x, [base=math.e])
    Return the logarithm of x to the given base.
    
    If the base not specified, returns the natural logarithm (base e) of x.



In [96]:
from math import *
print(pi, log(32, 2))

3.141592653589793 5.0


In [135]:
import numpy
# Roll 10 dice
rolls = numpy.random.randint(low=1, high=7, size=10)
rolls, type(rolls), print(dir(rolls)),help(rolls.ravel), rolls.tolist()

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift_

(array([5, 3, 2, 3, 1, 3, 4, 6, 3, 2]),
 numpy.ndarray,
 None,
 None,
 [5, 3, 2, 3, 1, 3, 4, 6, 3, 2])

In [142]:
rolls + 10 , rolls <= 3
xlist = [[1,2,3],[2,4,6],]
# Create a 2-dimensional array
x = numpy.asarray(xlist)
print("xlist = {}\nx =\n{}".format(xlist, x))

xlist = [[1, 2, 3], [2, 4, 6]]
x =
[[1 2 3]
 [2 4 6]]


In [3]:
# print(dir(numpy))
import tensorflow as tf
# Create two constants, each with value 1
a = tf.constant(1)
b = tf.constant(1)
# Add them together to get...
a + b

ImportError: Traceback (most recent call last):
  File "C:\Users\Mojtaba\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

In [7]:
full_dataset= [{'name': 'Peach', 'items': ['green shell', 'banana', 'green shell'], 'finish': 3}, 
 {'name': 'Peach', 'items': ['green shell', 'banana', 'green shell'], 'finish': 1}, 
 {'name': 'Bowser', 'items': ['green shell'], 'finish': 1}, 
 {'name': None, 'items': ['green shell'], 'finish': 2}, 
 {'name': 'Bowser', 'items': ['green shell'], 'finish': 1},
 {'name': None, 'items': ['red shell'], 'finish': 1},
 {'name': 'Yoshi', 'items': ['banana', 'blue shell', 'banana'], 'finish': 7},
 {'name': 'DK', 'items': ['blue shell', 'star'], 'finish': 1}]

# Import luigi's full dataset of race data
# from learntools.python.luigi_analysis import full_dataset
# print(full_dataset)
# Fix me!
def best_items(racers):
    winner_item_counts = {}
    for i in range(len(racers)):
        # The i'th racer dictionary
        racer = racers[i]
        # We're only interested in racers who finished in first
        if racer['finish'] == 1:
            for it in racer['items']:
                # Add one to the count for this item (adding it to the dict if necessary)
                if it not in winner_item_counts:
                    winner_item_counts[it] = 0
                winner_item_counts[it] += 1
        print("i",type(i))
#         print("it",type(it))

    
        # Data quality issues :/ Print a warning about racers with no name set. We'll take care of it later.
        if racer['name'] is None:
            print("WARNING: Encountered racer with unknown name on iteration {}/{} (racer = {})".format(
                (i+1), (len(racers)), racer['name'])
                 )
    return winner_item_counts

# Try analyzing the imported full dataset
best_items(full_dataset)

i <class 'int'>
i <class 'int'>
i <class 'int'>
i <class 'int'>
i <class 'int'>
i <class 'int'>
i <class 'int'>
i <class 'int'>


{'green shell': 4, 'banana': 1, 'red shell': 1, 'blue shell': 1, 'star': 1}

In [8]:
hand1 = BlackjackHand(['K', 'A'])
hand2 = BlackjackHand(['7', '10', 'A'])
hand1 > hand2

NameError: name 'BlackjackHand' is not defined

In [3]:
conda install python-graphviz

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\Mojtaba\anaconda3

  added / updated specs:
    - python-graphviz


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.8.3                |           py37_0         2.8 MB
    graphviz-2.38              |       hfd603c8_2        29.3 MB
    python-graphviz-0.14       |             py_0          25 KB
    ------------------------------------------------------------
                                           Total:        32.2 MB

The following NEW packages will be INSTALLED:

  graphviz           pkgs/main/win-64::graphviz-2.38-hfd603c8_2
  python-graphviz    pkgs/main/noarch::python-graphviz-0.14-py_0

The following packages will be UPDATED:

  conda                                        4.8.2-py37_0 --> 4.8.3-py37_0




graphviz-2.38        | 29.3 MB   |            |   0% 
graphviz-2.38  